ALTER TABLE public.facturas ADD CONSTRAINT facturas_monto_recibido_non_negative CHECK (((monto_recibido IS NULL) OR (monto_recibido >= (0)::numeric))) NOT VALID;
ALTER TABLE public.facturas ADD CONSTRAINT facturas_cambio_devuelto_non_negative CHECK (((cambio_devuelto IS NULL) OR (cambio_devuelto >= (0)::numeric))) NOT VALID;
ALTER TABLE public.cuentas_pagar ADD CONSTRAINT cuentas_pagar_monto_total_check CHECK ((monto_total >= 0.00));
ALTER TABLE public.cuentas_pagar ADD CONSTRAINT cuentas_pagar_monto_pagado_check CHECK ((monto_pagado >= 0.00));
ALTER TABLE public.cuentas_pagar ADD CONSTRAINT cuentas_pagar_pkey PRIMARY KEY (id);
ALTER TABLE public.cuentas_pagar ADD CONSTRAINT cuentas_pagar_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.cuentas_pagar ADD CONSTRAINT cuentas_pagar_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.cuentas_pagar ADD CONSTRAINT cuentas_pagar_compra_id_fkey FOREIGN KEY (compra_id) REFERENCES compras(id) ON DELETE SET NULL;
ALTER TABLE public.payments ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE public.payments ADD CONSTRAINT payments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.measurement_units ADD CONSTRAINT measurement_units_pkey PRIMARY KEY (id);
ALTER TABLE public.measurement_units ADD CONSTRAINT measurement_units_tenant_id_code_key UNIQUE (tenant_id, code);
ALTER TABLE public.measurement_units ADD CONSTRAINT measurement_units_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.- ADD CONSTRAINT content_type_check CHECK ((VALUE ~ '^\S+\/\S+'::text));
ALTER TABLE public.consumos ADD CONSTRAINT consumos_pkey PRIMARY KEY (id);
ALTER TABLE public.consumos ADD CONSTRAINT consumos_comanda_id_fkey FOREIGN KEY (comanda_id) REFERENCES comandas(id) ON DELETE SET NULL;
ALTER TABLE public.consumos ADD CONSTRAINT consumos_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES facturas(id) ON DELETE SET NULL;
ALTER TABLE public.consumos ADD CONSTRAINT consumos_plato_id_fkey FOREIGN KEY (plato_id) REFERENCES platos(id) ON DELETE RESTRICT;
ALTER TABLE public.platos ADD CONSTRAINT platos_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE public.cocina_estado ADD CONSTRAINT cocina_estado_pkey PRIMARY KEY (id);
ALTER TABLE public.comandas ADD CONSTRAINT comandas_pkey PRIMARY KEY (id);
ALTER TABLE public.platos ADD CONSTRAINT platos_pkey PRIMARY KEY (id);
ALTER TABLE public.facturas ADD CONSTRAINT facturas_estado_check CHECK (((estado)::text = ANY ((ARRAY['pendiente'::character varying, 'pagada'::character varying, 'cancelada'::character varying])::text[])));
ALTER TABLE public.facturas ADD CONSTRAINT facturas_pkey PRIMARY KEY (id);
ALTER TABLE public.tenants ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);
ALTER TABLE public.cuentas_pagar ADD CONSTRAINT cuentas_pagar_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES proveedores(id) ON DELETE CASCADE;
ALTER TABLE public.cxp_pagos ADD CONSTRAINT cxp_pagos_monto_check CHECK ((monto > 0.00));
ALTER TABLE public.cxp_pagos ADD CONSTRAINT cxp_pagos_pkey PRIMARY KEY (id);
ALTER TABLE public.cxp_pagos ADD CONSTRAINT cxp_pagos_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.facturas ADD CONSTRAINT facturas_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE public.sucursales ADD CONSTRAINT sucursales_pkey PRIMARY KEY (id);
ALTER TABLE public.sucursales ADD CONSTRAINT sucursales_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.productos_inventario ADD CONSTRAINT productos_inventario_pkey PRIMARY KEY (id);
ALTER TABLE public.productos_inventario ADD CONSTRAINT productos_inventario_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.productos_inventario ADD CONSTRAINT productos_inventario_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.inventario_movimientos ADD CONSTRAINT inventario_movimientos_pkey PRIMARY KEY (id);
ALTER TABLE public.inventario_movimientos ADD CONSTRAINT inventario_movimientos_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.inventario_movimientos ADD CONSTRAINT inventario_movimientos_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.inventario_movimientos ADD CONSTRAINT inventario_movimientos_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES productos_inventario(id) ON DELETE CASCADE;
ALTER TABLE public.inventario_movimientos ADD CONSTRAINT inventario_movimientos_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES tenant_users(id) ON DELETE SET NULL;
ALTER TABLE public.recetas ADD CONSTRAINT recetas_pkey PRIMARY KEY (id);
ALTER TABLE public.recetas ADD CONSTRAINT recetas_plato_id_insumo_id_key UNIQUE (plato_id, insumo_id);
ALTER TABLE public.recetas ADD CONSTRAINT recetas_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.recetas ADD CONSTRAINT recetas_plato_id_fkey FOREIGN KEY (plato_id) REFERENCES platos(id) ON DELETE CASCADE;
ALTER TABLE public.recetas ADD CONSTRAINT recetas_insumo_id_fkey FOREIGN KEY (insumo_id) REFERENCES productos_inventario(id) ON DELETE CASCADE;
ALTER TABLE public.produccion_cocina ADD CONSTRAINT produccion_cocina_pkey PRIMARY KEY (id);
ALTER TABLE public.produccion_cocina ADD CONSTRAINT produccion_cocina_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.produccion_cocina ADD CONSTRAINT produccion_cocina_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.produccion_cocina ADD CONSTRAINT produccion_cocina_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES productos_inventario(id) ON DELETE CASCADE;
ALTER TABLE public.platos ADD CONSTRAINT platos_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.menu_categories ADD CONSTRAINT menu_categories_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.mesas_estado ADD CONSTRAINT mesas_estado_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.comandas ADD CONSTRAINT comandas_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.consumos ADD CONSTRAINT consumos_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.facturas ADD CONSTRAINT facturas_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.cierres_operativos ADD CONSTRAINT cierres_operativos_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.gastos ADD CONSTRAINT gastos_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.gasto_categorias ADD CONSTRAINT gasto_categorias_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.cocina_estado ADD CONSTRAINT cocina_estado_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.cxp_pagos ADD CONSTRAINT cxp_pagos_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.cxp_pagos ADD CONSTRAINT cxp_pagos_cuenta_pagar_id_fkey FOREIGN KEY (cuenta_pagar_id) REFERENCES cuentas_pagar(id) ON DELETE CASCADE;
ALTER TABLE public.comandas ADD CONSTRAINT comandas_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE public.consumos ADD CONSTRAINT consumos_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE public.cocina_estado ADD CONSTRAINT cocina_estado_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE public.tenant_users ADD CONSTRAINT tenant_users_pkey PRIMARY KEY (id);
ALTER TABLE public.tenant_users ADD CONSTRAINT tenant_users_tenant_id_email_key UNIQUE (tenant_id, email);
ALTER TABLE public.tenant_users ADD CONSTRAINT tenant_users_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.mesas_estado ADD CONSTRAINT mesas_estado_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.tenant_users ADD CONSTRAINT fk_tenant_users_auth_user FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.mesas_estado ADD CONSTRAINT mesas_estado_pkey PRIMARY KEY (tenant_id, id);
ALTER TABLE public.cierres_operativos ADD CONSTRAINT cierres_operativos_cycle_number_check CHECK ((cycle_number > 0));
ALTER TABLE public.cierres_operativos ADD CONSTRAINT cierres_operativos_closed_after_open CHECK (((closed_at IS NULL) OR (closed_at >= opened_at)));
ALTER TABLE public.cierres_operativos ADD CONSTRAINT cierres_operativos_printed_after_open CHECK (((printed_at IS NULL) OR (printed_at >= opened_at)));
ALTER TABLE public.cierres_operativos ADD CONSTRAINT cierres_operativos_pkey PRIMARY KEY (id);
ALTER TABLE public.cierres_operativos ADD CONSTRAINT cierres_operativos_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.gasto_categorias ADD CONSTRAINT gasto_categorias_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.gastos ADD CONSTRAINT gastos_descripcion_not_blank CHECK ((length(TRIM(BOTH FROM descripcion)) > 0));
ALTER TABLE public.cxp_pagos ADD CONSTRAINT cxp_pagos_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES cierres_operativos(id) ON DELETE SET NULL;
ALTER TABLE public.cxp_pagos ADD CONSTRAINT cxp_pagos_created_by_auth_user_id_fkey FOREIGN KEY (created_by_auth_user_id) REFERENCES tenant_users(id) ON DELETE SET NULL;
ALTER TABLE public.tenants ADD CONSTRAINT tenants_plan_allowed CHECK (((plan)::text = ANY ((ARRAY['basico'::character varying, 'profesional'::character varying, 'empresarial'::character varying])::text[])));
ALTER TABLE public.digital_menu_settings ADD CONSTRAINT digital_menu_settings_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.digital_menu_items ADD CONSTRAINT digital_menu_items_pkey PRIMARY KEY (id);
ALTER TABLE public.cyberbistro_super_admins ADD CONSTRAINT cyberbistro_super_admins_pkey PRIMARY KEY (auth_user_id);
ALTER TABLE public.cyberbistro_super_admins ADD CONSTRAINT cyberbistro_super_admins_email_key UNIQUE (email);
ALTER TABLE public.menu_categories ADD CONSTRAINT menu_categories_nombre_not_blank CHECK ((length(TRIM(BOTH FROM nombre)) > 0));
ALTER TABLE public.menu_categories ADD CONSTRAINT menu_categories_color_hex CHECK ((color ~ '^#[0-9A-Fa-f]{6}$'::text));
ALTER TABLE public.menu_categories ADD CONSTRAINT menu_categories_pkey PRIMARY KEY (id);
ALTER TABLE public.menu_categories ADD CONSTRAINT menu_categories_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.gasto_categorias ADD CONSTRAINT gasto_categorias_nombre_not_blank CHECK ((length(TRIM(BOTH FROM nombre)) > 0));
ALTER TABLE public.gasto_categorias ADD CONSTRAINT gasto_categorias_pkey PRIMARY KEY (id);
ALTER TABLE public.gastos ADD CONSTRAINT gastos_monto_positive CHECK ((monto > (0)::numeric));
ALTER TABLE public.gastos ADD CONSTRAINT gastos_pkey PRIMARY KEY (id);
ALTER TABLE public.gastos ADD CONSTRAINT gastos_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.gastos ADD CONSTRAINT gastos_category_id_fkey FOREIGN KEY (category_id) REFERENCES gasto_categorias(id) ON DELETE SET NULL;
ALTER TABLE public.gastos ADD CONSTRAINT gastos_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES cierres_operativos(id) ON DELETE SET NULL;
ALTER TABLE public.tenants ADD CONSTRAINT tenants_logo_size_px_range CHECK (((logo_size_px >= 32) AND (logo_size_px <= 90))) NOT VALID;
ALTER TABLE public.tenants ADD CONSTRAINT tenants_logo_offset_x_range CHECK (((logo_offset_x >= '-28'::integer) AND (logo_offset_x <= 28))) NOT VALID;
ALTER TABLE public.tenants ADD CONSTRAINT tenants_logo_offset_y_range CHECK (((logo_offset_y >= '-12'::integer) AND (logo_offset_y <= 18))) NOT VALID;
ALTER TABLE public.cloudix_super_admins ADD CONSTRAINT cloudix_super_admins_pkey PRIMARY KEY (auth_user_id);
ALTER TABLE public.cloudix_super_admins ADD CONSTRAINT cloudix_super_admins_email_key UNIQUE (email);
ALTER TABLE public.tenants ADD CONSTRAINT tenants_admin_user_limit_check CHECK (((admin_user_limit IS NULL) OR (admin_user_limit >= 0)));
ALTER TABLE public.tenants ADD CONSTRAINT tenants_cajera_user_limit_check CHECK (((cajera_user_limit IS NULL) OR (cajera_user_limit >= 0)));
ALTER TABLE public.tenants ADD CONSTRAINT tenants_cocina_user_limit_check CHECK (((cocina_user_limit IS NULL) OR (cocina_user_limit >= 0)));
ALTER TABLE public.tenants ADD CONSTRAINT tenants_mesero_user_limit_check CHECK (((mesero_user_limit IS NULL) OR (mesero_user_limit >= 0)));
ALTER TABLE public.customers ADD CONSTRAINT customers_pkey PRIMARY KEY (id);
ALTER TABLE public.customers ADD CONSTRAINT customers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.facturas ADD CONSTRAINT facturas_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL;
ALTER TABLE public.cuentas_cobrar ADD CONSTRAINT cuentas_cobrar_monto_total_check CHECK ((monto_total >= 0.00));
ALTER TABLE public.digital_menu_items ADD CONSTRAINT digital_menu_items_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.digital_menu_items ADD CONSTRAINT digital_menu_items_plato_id_fkey FOREIGN KEY (plato_id) REFERENCES platos(id) ON DELETE CASCADE;
ALTER TABLE public.digital_orders ADD CONSTRAINT digital_orders_total_check CHECK ((total >= 0.00));
ALTER TABLE public.digital_orders ADD CONSTRAINT digital_orders_pkey PRIMARY KEY (id);
ALTER TABLE public.digital_orders ADD CONSTRAINT digital_orders_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.digital_orders ADD CONSTRAINT digital_orders_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.digital_order_items ADD CONSTRAINT digital_order_items_price_snapshot_check CHECK ((price_snapshot >= 0.00));
ALTER TABLE public.permission_catalog ADD CONSTRAINT permission_catalog_pkey PRIMARY KEY (id);
ALTER TABLE public.permission_catalog ADD CONSTRAINT permission_catalog_permission_key_key UNIQUE (permission_key);
ALTER TABLE public.digital_order_items ADD CONSTRAINT digital_order_items_quantity_check CHECK ((quantity > 0));
ALTER TABLE public.digital_order_items ADD CONSTRAINT digital_order_items_subtotal_check CHECK ((subtotal >= 0.00));
ALTER TABLE public.digital_order_items ADD CONSTRAINT digital_order_items_pkey PRIMARY KEY (id);
ALTER TABLE public.digital_order_items ADD CONSTRAINT digital_order_items_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.digital_order_items ADD CONSTRAINT digital_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES digital_orders(id) ON DELETE CASCADE;
ALTER TABLE public.proveedores ADD CONSTRAINT proveedores_pkey PRIMARY KEY (id);
ALTER TABLE public.proveedores ADD CONSTRAINT proveedores_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.compras ADD CONSTRAINT compras_pkey PRIMARY KEY (id);
ALTER TABLE public.compras ADD CONSTRAINT compras_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.compras ADD CONSTRAINT compras_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.compras ADD CONSTRAINT compras_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES proveedores(id) ON DELETE SET NULL;
ALTER TABLE public.compras ADD CONSTRAINT compras_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES tenant_users(id) ON DELETE SET NULL;
ALTER TABLE public.compra_detalles ADD CONSTRAINT compra_detalles_pkey PRIMARY KEY (id);
ALTER TABLE public.compra_detalles ADD CONSTRAINT compra_detalles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.compra_detalles ADD CONSTRAINT compra_detalles_compra_id_fkey FOREIGN KEY (compra_id) REFERENCES compras(id) ON DELETE CASCADE;
ALTER TABLE public.compra_detalles ADD CONSTRAINT compra_detalles_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES productos_inventario(id) ON DELETE CASCADE;
ALTER TABLE public.cuentas_cobrar ADD CONSTRAINT cuentas_cobrar_monto_pagado_check CHECK ((monto_pagado >= 0.00));
ALTER TABLE public.cuentas_cobrar ADD CONSTRAINT cuentas_cobrar_pkey PRIMARY KEY (id);
ALTER TABLE public.cuentas_cobrar ADD CONSTRAINT cuentas_cobrar_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.cuentas_cobrar ADD CONSTRAINT cuentas_cobrar_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.cuentas_cobrar ADD CONSTRAINT cuentas_cobrar_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES facturas(id) ON DELETE SET NULL;
ALTER TABLE public.cuentas_cobrar ADD CONSTRAINT cuentas_cobrar_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
ALTER TABLE public.cxc_pagos ADD CONSTRAINT cxc_pagos_monto_check CHECK ((monto > 0.00));
ALTER TABLE public.cxc_pagos ADD CONSTRAINT cxc_pagos_pkey PRIMARY KEY (id);
ALTER TABLE public.cxc_pagos ADD CONSTRAINT cxc_pagos_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.cxc_pagos ADD CONSTRAINT cxc_pagos_sucursal_id_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE SET NULL;
ALTER TABLE public.cxc_pagos ADD CONSTRAINT cxc_pagos_cuenta_cobrar_id_fkey FOREIGN KEY (cuenta_cobrar_id) REFERENCES cuentas_cobrar(id) ON DELETE CASCADE;
ALTER TABLE public.cxc_pagos ADD CONSTRAINT cxc_pagos_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES cierres_operativos(id) ON DELETE SET NULL;
ALTER TABLE public.cxc_pagos ADD CONSTRAINT cxc_pagos_created_by_auth_user_id_fkey FOREIGN KEY (created_by_auth_user_id) REFERENCES tenant_users(id) ON DELETE SET NULL;
ALTER TABLE public.tenants ADD CONSTRAINT tenants_sucursal_limit_non_negative CHECK (((sucursal_limit IS NULL) OR (sucursal_limit >= 1)));
ALTER TABLE public.digital_menu_settings ADD CONSTRAINT digital_menu_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.digital_menu_settings ADD CONSTRAINT digital_menu_settings_public_slug_key UNIQUE (public_slug);
ALTER TABLE public.digital_menu_settings ADD CONSTRAINT digital_menu_settings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.digital_order_items ADD CONSTRAINT digital_order_items_plato_id_fkey FOREIGN KEY (plato_id) REFERENCES platos(id) ON DELETE SET NULL;
ALTER TABLE public.fiscal_outbox ADD CONSTRAINT fiscal_outbox_attempts_check CHECK ((attempts >= 0));
ALTER TABLE public.tenants ADD CONSTRAINT tenants_ecf_environment_check CHECK ((ecf_environment = ANY (ARRAY['test'::text, 'certification'::text, 'production'::text])));
ALTER TABLE public.tenants ADD CONSTRAINT tenants_fiscal_mode_check CHECK ((fiscal_mode = ANY (ARRAY['internal_receipt'::text, 'ncf_legacy'::text, 'dgii_ecf'::text])));
ALTER TABLE public.tenants ADD CONSTRAINT tenants_fiscal_mode_fallback_check CHECK (((fiscal_mode_fallback IS NULL) OR (fiscal_mode_fallback = ANY (ARRAY['internal_receipt'::text, 'ncf_legacy'::text]))));
ALTER TABLE public.ecf_e32_readiness_evidence ADD CONSTRAINT ecf_e32_readiness_evidence_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.ecf_certificate_metadata ADD CONSTRAINT ecf_certificate_metadata_environment_check CHECK ((environment = ANY (ARRAY['test'::text, 'certification'::text, 'production'::text])));
ALTER TABLE public.ecf_certificate_metadata ADD CONSTRAINT ecf_certificate_metadata_pkey PRIMARY KEY (id);
ALTER TABLE public.ecf_certificate_metadata ADD CONSTRAINT ecf_certificate_metadata_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.ecf_documents ADD CONSTRAINT ecf_documents_pkey PRIMARY KEY (id);
ALTER TABLE public.ecf_documents ADD CONSTRAINT ecf_documents_tenant_factura_unique UNIQUE (tenant_id, factura_id);
ALTER TABLE public.ecf_documents ADD CONSTRAINT ecf_documents_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.ecf_documents ADD CONSTRAINT ecf_documents_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES facturas(id) ON DELETE RESTRICT;
ALTER TABLE public.ecf_documents ADD CONSTRAINT ecf_documents_certificate_metadata_id_fkey FOREIGN KEY (certificate_metadata_id) REFERENCES ecf_certificate_metadata(id) ON DELETE SET NULL;
ALTER TABLE public.ecf_document_events ADD CONSTRAINT ecf_document_events_pkey PRIMARY KEY (id);
ALTER TABLE public.ecf_document_events ADD CONSTRAINT ecf_document_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.ecf_document_events ADD CONSTRAINT ecf_document_events_ecf_document_id_fkey FOREIGN KEY (ecf_document_id) REFERENCES ecf_documents(id) ON DELETE CASCADE;
ALTER TABLE public.fiscal_outbox ADD CONSTRAINT fiscal_outbox_operation_check CHECK ((operation = ANY (ARRAY['submit'::text, 'poll_status'::text, 'resubmit'::text])));
ALTER TABLE public.fiscal_outbox ADD CONSTRAINT fiscal_outbox_pkey PRIMARY KEY (id);
ALTER TABLE public.fiscal_outbox ADD CONSTRAINT fiscal_outbox_idempotency_key_unique UNIQUE (idempotency_key);
ALTER TABLE public.fiscal_outbox ADD CONSTRAINT fiscal_outbox_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.fiscal_outbox ADD CONSTRAINT fiscal_outbox_ecf_document_id_fkey FOREIGN KEY (ecf_document_id) REFERENCES ecf_documents(id) ON DELETE CASCADE;
ALTER TABLE public.fiscal_outbox ADD CONSTRAINT fiscal_outbox_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES facturas(id) ON DELETE RESTRICT;
ALTER TABLE public.ecf_sequence_allocations ADD CONSTRAINT ecf_sequence_allocations_tipo_check CHECK ((tipo_ecf = ANY (ARRAY['E31'::text, 'E32'::text, 'E33'::text, 'E34'::text, 'E41'::text, 'E43'::text, 'E44'::text, 'E45'::text, 'E46'::text, 'E47'::text])));
ALTER TABLE public.ecf_sequence_allocations ADD CONSTRAINT ecf_sequence_allocations_status_check CHECK ((status = ANY (ARRAY['active'::text, 'exhausted'::text, 'revoked'::text])));
ALTER TABLE public.ecf_sequence_allocations ADD CONSTRAINT ecf_sequence_allocations_pkey PRIMARY KEY (id);
ALTER TABLE public.ecf_sequence_allocations ADD CONSTRAINT ecf_sequence_allocations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.ecf_e32_readiness_evidence ADD CONSTRAINT ecf_e32_readiness_requires_full_approval CHECK (((approved_at IS NULL) OR ((e32_validated IS TRUE) AND (rfce_validated IS TRUE) AND (resumen_validated IS TRUE))));
ALTER TABLE public.ecf_e32_readiness_evidence ADD CONSTRAINT ecf_e32_readiness_evidence_pkey PRIMARY KEY (id);
ALTER TABLE public.ecf_batches ADD CONSTRAINT ecf_batches_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'submitted'::text, 'accepted'::text, 'rejected'::text, 'retryable_error'::text, 'terminal_error'::text])));
ALTER TABLE public.ecf_batches ADD CONSTRAINT ecf_batches_pkey PRIMARY KEY (id);
ALTER TABLE public.ecf_batches ADD CONSTRAINT ecf_batches_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.ecf_documents ADD CONSTRAINT ecf_documents_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES ecf_batches(id) ON DELETE SET NULL;
ALTER TABLE public.facturas ADD CONSTRAINT facturas_fiscal_mode_check CHECK ((fiscal_mode = ANY (ARRAY['internal_receipt'::text, 'ncf_legacy'::text, 'dgii_ecf'::text])));
ALTER TABLE public.ecf_documents ADD CONSTRAINT ecf_documents_rejection_scope_check CHECK (((rejection_scope IS NULL) OR (rejection_scope = ANY (ARRAY['individual'::text, 'batch'::text]))));
ALTER TABLE public.ecf_documents ADD CONSTRAINT ecf_documents_status_check CHECK ((status = ANY (ARRAY['pending_offline'::text, 'pending_sync'::text, 'queued'::text, 'signed'::text, 'submitted'::text, 'accepted'::text, 'rejected'::text, 'retryable_error'::text, 'terminal_error'::text, 'pending_configuration'::text, 'pending_rfce_batch'::text])));
ALTER TABLE public.fiscal_outbox ADD CONSTRAINT fiscal_outbox_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'processing'::text, 'retryable_error'::text, 'terminal_error'::text, 'done'::text, 'blocked_configuration'::text])));
ALTER TABLE public.ecf_document_events ADD CONSTRAINT ecf_document_events_to_status_check CHECK ((to_status = ANY (ARRAY['pending_offline'::text, 'pending_sync'::text, 'queued'::text, 'signed'::text, 'submitted'::text, 'accepted'::text, 'rejected'::text, 'retryable_error'::text, 'terminal_error'::text, 'pending_configuration'::text, 'pending_rfce_batch'::text])));
ALTER TABLE public.ecf_document_events ADD CONSTRAINT ecf_document_events_from_status_check CHECK (((from_status IS NULL) OR (from_status = ANY (ARRAY['pending_offline'::text, 'pending_sync'::text, 'queued'::text, 'signed'::text, 'submitted'::text, 'accepted'::text, 'rejected'::text, 'retryable_error'::text, 'terminal_error'::text, 'pending_configuration'::text, 'pending_rfce_batch'::text]))));
ALTER TABLE public.cierres_operativos ADD CONSTRAINT cierres_operativos_efectivo_inicial_bounds CHECK (((efectivo_inicial >= (0)::numeric) AND (efectivo_inicial <= 9999999999.99)));
ALTER TABLE public.digital_orders ADD CONSTRAINT digital_orders_order_type_check CHECK ((order_type = ANY (ARRAY['takeout'::text, 'in_store'::text])));
ALTER TABLE public.tenant_order_counters ADD CONSTRAINT tenant_order_counters_pkey PRIMARY KEY (tenant_id);
ALTER TABLE public.tenant_order_counters ADD CONSTRAINT tenant_order_counters_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public.tenants ADD CONSTRAINT tenants_payment_day_of_month_check CHECK (((payment_day_of_month IS NULL) OR ((payment_day_of_month >= 1) AND (payment_day_of_month <= 31))));